"""Plain-text report templates.

Kept separate from the exporter so the layout can be unit-tested without
touching the filesystem, and so future formats (CSV/HTML) can reuse the
same report dictionary.
"""

from __future__ import annotations

from typing import Dict

from webbehavior.utils.helpers import format_ms, format_seconds

__all__ = ["render_txt_report", "render_session_lines"]

_WIDTH = 46


def _row(label: str, value: str) -> str:
    return " {:<13}: {}".format(label, value)


def _rule(char: str = "─") -> str:
    return char * _WIDTH


def render_session_lines(report: Dict) -> str:
    """Per-session detail block used inside the TXT report."""
    lines = []
    for session in report.get("sessions", []):
        status = session.get("status", "--")
        symbol = {"SUCCESS": "✓", "FAILED": "✗"}.get(status, "○")
        lines.append(
            " {} Session {:>2}  {}  http={}  resp={}  dur={}".format(
                symbol,
                session.get("index", "?"),
                status,
                session.get("http_status") or "--",
                format_ms(session.get("response_time_ms")),
                format_seconds(session.get("duration_s")),
            )
        )
    return "\n".join(lines) if lines else " (no session data)"


def render_txt_report(report: Dict) -> str:
    """Render a complete plain-text report (PRD 10 layout)."""
    summary = report.get("summary", {}) or {}
    meta = report.get("meta", {}) or {}
    lines = [
        "╭" + _rule("─") + "╮",
        "│{:^44}│".format("TEST COMPLETE"),
        "╰" + _rule("─") + "╯",
        "",
        _row("Test ID", str(report.get("test_id", "--"))),
        _row("Target", str(meta.get("target", "--"))),
        _row("Started", str(meta.get("started_at", "--"))),
        "",
        _row("Sessions", str(summary.get("sessions", 0))),
        _row("Successful", str(summary.get("successful", 0))),
        _row("Failed", str(summary.get("failed", 0))),
        _row("Status", str(summary.get("status", "--"))),
        "",
        _row("Avg Latency", format_ms(summary.get("avg_latency_ms"))),
        _row("Max Latency", format_ms(summary.get("max_latency_ms"))),
        _row("Min Latency", format_ms(summary.get("min_latency_ms"))),
        _row("Total Time", format_seconds(summary.get("total_duration_s"))),
        "",
        " Sessions",
        render_session_lines(report),
        "",
        " Actions/Events",
        _row("Actions", str(summary.get("total_actions", 0))),
        _row("Events", str(summary.get("total_events", 0))),
        "",
        " Generated by WebBehaviorLab v{} - educational testing only.".format(
            report.get("version", "1.0.0")
        ),
    ]
    return "\n".join(lines) + "\n"
